version: '3.8'

services:
  apache:
    build:
      context: ./apache
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - postgres

  symfony:
    build:
      context: ./symfony
    volumes:
      - ./symfony:/var/www/html
    working_dir: /var/www/html
    command: >
      sh -c "composer install && php bin/console cache:clear && php -S 0.0.0.0:8000 -t public"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mfadb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    build:
      context: ./pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
